config/routes.rb
Rails.application.routes.draw do

	resources :users, :algebras, :lowers, :uppers, :business_maths, :proofs, :precalcs, :linears

	get 'algebra/dashboard/:id'                  => 'algebras#dashboard',         as: 'dash_algebras'
	get 'algebra/quiz/:id'                       => 'algebras#quiz',              as: 'quiz_algebras'
	get 'algebra/practice/:id'                   => 'algebras#practice',          as: 'practice_algebras'
	get 'algebra/practice/equations/:id'         => 'algebras#equations',         as: 'equations_algebras'
	get 'algebra/practice/inequalities/:id'      => 'algebras#inequalities',      as: 'inequalities_algebras'
	get 'algebra/practice/systems/:id'           => 'algebras#systems',           as: 'systems_algebras'
	get 'algebra/practice/factoring/:id'         => 'algebras#factoring',         as: 'factoring_algebras'
	get 'algebra/practice/quadratic/:id'         => 'algebras#quadratic',         as: 'quadratic_algebras'
	get 'algebra/practice/exponents/:id'         => 'algebras#exponents',         as: 'exponents_algebras'
	get 'algebra/practice/functions/:id'         => 'algebras#functions',         as: 'functions_algebras'

	get 'finite_math/dashboard/:id'              => 'business_maths#dashboard',   as: 'dash_business_maths'
	get 'finite_math/quiz/:id'                   => 'business_maths#quiz',        as: 'quiz_business_maths'
	get 'finite_math/practice/:id'               => 'business_maths#practice',    as: 'practice_business_maths'
	get 'finite_math/practice/equations/:id'     => 'business_maths#equations',   as: 'equations_business_maths'
	get 'finite_math/practice/programming/:id'   => 'business_maths#programming', as: 'programming_business_maths'
	get 'finite_math/practice/interest/:id'      => 'business_maths#interest',    as: 'interest_business_maths'
	get 'finite_math/practice/probability/:id'   => 'business_maths#probability', as: 'probability_business_maths'
	get 'finite_math/practice/matrices/:id'      => 'business_maths#matrices',    as: 'matrices_business_maths'

	get 'linear/dashboard/:id'                   => 'linears#dashboard',          as: 'dash_linears'
	get 'linear/quiz/:id'                        => 'linears#quiz',               as: 'quiz_linears'
	get 'linear/practice/:id'                    => 'linears#practice',           as: 'practice_linears'
	get 'linear/practice/vector_spaces/:id'      => 'linears#vector_spaces',      as: 'vector_spaces_linears'
	get 'linear/practice/transformations/:id'    => 'linears#transformations',    as: 'transformations_linears'
	get 'linear/practice/basis/:id'              => 'linears#basis',              as: 'basis_linears'
	get 'linear/practice/matrices/:id'           => 'linears#matrices',           as: 'matrices_linears'
	get 'linear/practice/eigenvectors/:id'       => 'linears#eigenvectors',       as: 'eigenvectors_linears'
	get 'linear/practice/inner_products/:id'     => 'linears#inner_products',     as: 'inner_products_linears'

	get 'isee_lower/dashboard/:id'               => 'lowers#dashboard',           as: 'dash_lowers'
	get 'isee_lower/quiz/:id'                    => 'lowers#quiz',                as: 'quiz_lowers'
	get 'isee_lower/practice/:id'                => 'lowers#practice',            as: 'practice_lowers'
	get 'isee_lower/practice/math/:id'           => 'lowers#math',                as: 'math_lowers'
	get 'isee_lower/practice/reading/:id'        => 'lowers#reading',             as: 'reading_lowers'
	get 'isee_lower/practice/writing/:id'        => 'lowers#writing',             as: 'writing_lowers'

	get 'isee_upper/dashboard/:id'               => 'uppers#dashboard',         as: 'dash_uppers'
	get 'isee_upper/quiz/:id'                    => 'uppers#quiz',              as: 'quiz_uppers'
	get 'isee_upper/practice/:id'                => 'uppers#practice',          as: 'practice_uppers'
	get 'isee_upper/practice/math/:id'           => 'uppers#math',              as: 'math_uppers'
	get 'isee_upper/practice/reading/:id'        => 'uppers#reading',           as: 'reading_uppers'
	get 'isee_upper/practice/writing/:id'        => 'uppers#writing',           as: 'writing_uppers'

	get 'precalc/dashboard/:id'			 	 	         => 'precalcs#dashboard',       as: 'dash_precalcs'
	get 'precalc/quiz/:id'       					       => 'precalcs#quiz',            as: 'quiz_precalcs'
	get 'precalc/practice/:id'   					       => 'precalcs#practice',        as: 'practice_precalcs'
	get 'precalc/practice/functions/:id'         => 'precalcs#functions',       as: 'functions_precalcs'
	get 'precalc/practice/logs/:id'              => 'precalcs#logs',            as: 'logs_precalcs'
	get 'precalc/practice/triangles/:id'         => 'precalcs#triangles',       as: 'triangles_precalcs'
	get 'precalc/practice/sine/:id'              => 'precalcs#sine',            as: 'sine_precalcs'
	get 'precalc/practice/trig/:id'              => 'precalcs#trig',            as: 'trig_precalcs'
	get 'precalc/practice/systems/:id'           => 'precalcs#systems',         as: 'systems_precalcs'

	get 'proofs/dashboard/:id'                   => 'proofs#dashboard',         as: 'dash_proofs'
	get 'proofs/quiz/:id'                        => 'proofs#quiz',              as: 'quiz_proofs'
	get 'proofs/practice/:id'                    => 'proofs#practice',          as: 'practice_proofs'
	get 'proofs/practice/logic/:id'              => 'proofs#logic',             as: 'logic_proofs'
	get 'proofs/practice/induction/:id'          => 'proofs#induction',         as: 'induction_proofs'
	get 'proofs/practice/relations/:id'          => 'proofs#relations',         as: 'relations_proofs'
	get 'proofs/practice/functions/:id'          => 'proofs#functions',         as: 'functions_proofs'
	get 'proofs/practice/cardinality/:id'        => 'proofs#cardinality',       as: 'cardinality_proofs'
	get 'proofs/practice/modulo/:id'             => 'proofs#modulo',            as: 'modulo_proofs'
	get 'proofs/practice/algebra/:id'            => 'proofs#algebra',           as: 'algebra_proofs'

	resource :sessions, only: [:new, :create, :destroy]

	root 'sessions#new'

end

app/models/linear.rb
class Linear < ActiveRecord::Base
end

app/controllers/linears_controller.rb
class LinearsController < ApplicationController

	def index
		@linears = Linear.all
	end

	def dashboard
		@user = User.find(session['user_id'])
	end

	def practice
		@user = User.find(session['user_id'])
		@linears = Linear.where(question_type:'practice')
	end

	def quiz
		@user = User.find(session['user_id'])
		@linears = Linear.where(question_type:'quiz')
	end

	def new
		@linear = Linear.new
	end

	def create
		@linear = Linear.create(linear_params)
		if @linear.save
			redirect_to linears_path
		else
			render 'new'
		end
	end

	def show
		@linear = Linear.find(params[:id])
	end

	private
	def linear_params
		params.require(:linear).permit(:user_id, :question_type, :question, :solution, :answer_choices,
																	 :correct, :module_name)
	end

end

app/helpers/linears_helper.rb
module LinearsHelper
end

app/views/linears/_nav.html.erb
<nav class="navbar navbar-default"
		 xmlns="http://www.w3.org/1999/html">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<button type="button" class="btn btn-default navbar-btn navbar-right">
				<%= link_to 'Dashboard', user_path(session['user_id']), :style => 'font-decoration:none;color:#26aa30' %>
			</button>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
						Subjects <span class="caret"></span>
					</a>
					<ul class="dropdown-menu" role="menu">
						<li><%= link_to 'Algebra I', dash_algebras_path(session['user_id']) %></li>
						<li><%= link_to 'Finite Math', dash_business_maths_path(session['user_id']) %></li>
						<li><%= link_to 'ISEE - Lower', dash_lowers_path(session['user_id']) %></li>
						<li><%= link_to 'ISEE - Upper', dash_uppers_path(session['user_id']) %></li>
						<li><%= link_to 'Linear Algebra', dash_linears_path(session['user_id']) %></li>
						<li><%= link_to 'Precalculus', dash_precalcs_path(session['user_id']) %></li>
						<li><%= link_to 'Proof Writing', dash_proofs_path(session['user_id']) %></li>
					</ul>
				</li>
			</ul>

			<div class="btn-group">
				<button class="btn btn-info btn-sm">
					<%= link_to 'Linear Algebra', dash_linears_path(session['user_id']), style:"color:#f0f0f0" %>
				</button>
				<button class="btn btn-info btn-sm dropdown-toggle" data-toggle="dropdown"> <span class="caret"></span>
				</button>
				<ul class="dropdown-menu">
					<li><%= link_to 'Vector spaces', dash_linears_path(session['user_id']) %></li>
					<li><%= link_to 'Linear transformations', dash_linears_path(session['user_id']) %></li>
					<li><%= link_to 'Subspaces, span, and basis', dash_linears_path(session['user_id']) %></li>
					<li><%= link_to 'Matrix theory', dash_linears_path(session['user_id']) %></li>
					<li><%= link_to 'Eigenvalues and eignevectors', dash_linears_path(session['user_id']) %></li>
					<li><%= link_to 'Inner product spaces', dash_linears_path(session['user_id']) %></li>
				</ul>
			</div>

			<!--<ul class="nav navbar-nav navbar-right">-->
			<!--<li>Hello, <%#= @user.first_name.capitalize %>!</li>-->
			<!--</ul>-->
			<ul class="nav navbar-nav navbar-right"  style="color:#26aa30">
				<li>
					<!--<a href="#editProfileModal" data-toggle="modal" data-target="#editProfileModal">Edit profile</a>-->
					<%#= link_to 'Edit profile', edit_user_path(session['user_id']) %>
					<button type="button" class="btn btn-default navbar-btn navbar-right">
						<a href="#editProfileModal" data-toggle="modal" data-target="#editProfileModal">Edit profile</a>
					</button>
				</li>
				<li>
					<p class="navbar-name">Hello, <%= @user.first_name.capitalize %>!</p>
				</li>
			</ul>

			<button type="button" class="btn btn-default navbar-btn navbar-right">
				<%= link_to 'Log out', sessions_path, method: :delete, :style => 'font-decoration:none;color:#26aa30' %>
			</button>
		</div>
	</div>
</nav>


<div class="modal fade" id="editProfileModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h4 class="modal-title">Edit profile</h4>
			</div>
			<div class="modal-body">
				<div class="ruby-form">
					<%= form_for @user do |f| %>
						<%= f.text_field :first_name,   placeholder: 'First name', class:'form-input' %>
						<%= f.text_field :last_name,    placeholder: 'Last name',  class:'form-input' %><br><br>
						<%= f.text_field :email,        placeholder: 'Email',      class:'form-input' %><br><br>
						<%= f.submit 'Update profile!', 												   class:'btn btn-default btn-login btn-lg' %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/linears/dashboard.html.erb
<%= render 'nav' %>

  <div class="circles"> 
	<div class="row">
		<%= link_to practice_linears_path(session['user_id']) do %> 
			<div class="subject-circle col-md-6"> 
				<div class="subject">Practice Problems</div> 
			</div> 
		<% end %>
		<%= link_to quiz_linears_path(session['user_id']) do %> 
			<div class="subject-circle col-md-6"> 
				<div class="subject">Quiz</div>
			</div> 
		<% end %> 
	</div> 
</div>

  <ol class="breadcrumb"> 
	<li><%= link_to 'Dashboard', user_path(session['user_id']) %></li>
	<li class="active">Linear Algebra</li> 
</ol>

app/views/linears/practice.html.erb
<%= render 'nav' %>

<div class="circles">
	<div class="row">
		<%#= link_to functions_linears_path(session['user_id']) do %>
		<div class="subject-circle col-md-3">
			<div class="subject">Vector spaces</div>
		</div>
		<%# end %>

		<%#= link_to logs_linears_path(session['user_id']) do %>
		<div class="subject-circle col-md-3">
			<div class="subject">Linear transformations</div>
		</div>
		<%# end %>

		<%#= link_to triangles_linears_path(session['user_id']) do %>
		<div class="subject-circle col-md-3">
			<div class="subject">Subspaces, span, and basis</div>
		</div>
		<%# end %>

		<%#= link_to sine_linears_path(session['user_id']) do %>
		<div class="subject-circle col-md-3">
			<div class="subject">Matrix theory</div>
		</div>
		<%# end %>
	</div>

	<div class="row">
		<%#= link_to trig_linears_path(session['user_id']) do %>
		<div class="subject-circle col-md-3">
			<div class="subject">Eigenvalues and eigenvectors</div>
		</div>
		<%# end %>

		<%#= link_to systems_linears_path(session['user_id']) do %>
		<div class="subject-circle col-md-3">
			<div class="subject">Inner product spaces</div>
		</div>
		<%# end %>
	</div>
</div>

<ol class="breadcrumb">
	<li><%= link_to 'Dashboard', user_path(session['user_id']) %></li>
	<li><%= link_to 'Linear Algebra', dash_linears_path(session['user_id']) %></li>
	<li class="active">Practice</li>
</ol>

app/views/linears/quiz.html.erb
<%= render 'nav' %>

<ol class="breadcrumb">
	<li><%= link_to 'Dashboard', user_path(session['user_id']) %></li>
	<li><%= link_to 'Linear Algebra', dash_linears_path(session['user_id']) %></li>
	<li class="active">Quiz</li>
</ol>