config/routes.rb
Rails.application.routes.draw do

	resources :users, :algebras, :lowers, :uppers, :business_maths, :proofs, :precalcs, :linears

	get 'algebra/dashboard/:id'                  => 'algebras#dashboard',         as: 'dash_algebras'
	get 'algebra/quiz/:id'                       => 'algebras#quiz',              as: 'quiz_algebras'
	get 'algebra/practice/:id'                   => 'algebras#practice',          as: 'practice_algebras'
	get 'algebra/practice/equations/:id'         => 'algebras#equations',         as: 'equations_algebras'
	get 'algebra/practice/inequalities/:id'      => 'algebras#inequalities',      as: 'inequalities_algebras'
	get 'algebra/practice/systems/:id'           => 'algebras#systems',           as: 'systems_algebras'
	get 'algebra/practice/factoring/:id'         => 'algebras#factoring',         as: 'factoring_algebras'
	get 'algebra/practice/quadratic/:id'         => 'algebras#quadratic',         as: 'quadratic_algebras'
	get 'algebra/practice/exponents/:id'         => 'algebras#exponents',         as: 'exponents_algebras'
	get 'algebra/practice/functions/:id'         => 'algebras#functions',         as: 'functions_algebras'

	get 'finite_math/dashboard/:id'              => 'business_maths#dashboard',   as: 'dash_business_maths'
	get 'finite_math/quiz/:id'                   => 'business_maths#quiz',        as: 'quiz_business_maths'
	get 'finite_math/practice/:id'               => 'business_maths#practice',    as: 'practice_business_maths'
	get 'finite_math/practice/equations/:id'     => 'business_maths#equations',   as: 'equations_business_maths'
	get 'finite_math/practice/programming/:id'   => 'business_maths#programming', as: 'programming_business_maths'
	get 'finite_math/practice/interest/:id'      => 'business_maths#interest',    as: 'interest_business_maths'
	get 'finite_math/practice/probability/:id'   => 'business_maths#probability', as: 'probability_business_maths'
	get 'finite_math/practice/matrices/:id'      => 'business_maths#matrices',    as: 'matrices_business_maths'

	get 'linear/dashboard/:id'                   => 'linears#dashboard',          as: 'dash_linears'
	get 'linear/quiz/:id'                        => 'linears#quiz',               as: 'quiz_linears'
	get 'linear/practice/:id'                    => 'linears#practice',           as: 'practice_linears'
	get 'linear/practice/vector_spaces/:id'      => 'linears#vector_spaces',      as: 'vector_spaces_linears'
	get 'linear/practice/transformations/:id'    => 'linears#transformations',    as: 'transformations_linears'
	get 'linear/practice/basis/:id'              => 'linears#basis',              as: 'basis_linears'
	get 'linear/practice/matrices/:id'           => 'linears#matrices',           as: 'matrices_linears'
	get 'linear/practice/eigenvectors/:id'       => 'linears#eigenvectors',       as: 'eigenvectors_linears'
	get 'linear/practice/inner_products/:id'     => 'linears#inner_products',     as: 'inner_products_linears'

	get 'isee_lower/dashboard/:id'               => 'lowers#dashboard',           as: 'dash_lowers'
	get 'isee_lower/quiz/:id'                    => 'lowers#quiz',                as: 'quiz_lowers'
	get 'isee_lower/practice/:id'                => 'lowers#practice',            as: 'practice_lowers'
	get 'isee_lower/practice/math/:id'           => 'lowers#math',                as: 'math_lowers'
	get 'isee_lower/practice/reading/:id'        => 'lowers#reading',             as: 'reading_lowers'
	get 'isee_lower/practice/writing/:id'        => 'lowers#writing',             as: 'writing_lowers'

	get 'isee_upper/dashboard/:id'               => 'uppers#dashboard',         as: 'dash_uppers'
	get 'isee_upper/quiz/:id'                    => 'uppers#quiz',              as: 'quiz_uppers'
	get 'isee_upper/practice/:id'                => 'uppers#practice',          as: 'practice_uppers'
	get 'isee_upper/practice/math/:id'           => 'uppers#math',              as: 'math_uppers'
	get 'isee_upper/practice/reading/:id'        => 'uppers#reading',           as: 'reading_uppers'
	get 'isee_upper/practice/writing/:id'        => 'uppers#writing',           as: 'writing_uppers'

	get 'precalc/dashboard/:id'			 	 	         => 'precalcs#dashboard',       as: 'dash_precalcs'
	get 'precalc/quiz/:id'       					       => 'precalcs#quiz',            as: 'quiz_precalcs'
	get 'precalc/practice/:id'   					       => 'precalcs#practice',        as: 'practice_precalcs'
	get 'precalc/practice/functions/:id'         => 'precalcs#functions',       as: 'functions_precalcs'
	get 'precalc/practice/logs/:id'              => 'precalcs#logs',            as: 'logs_precalcs'
	get 'precalc/practice/triangles/:id'         => 'precalcs#triangles',       as: 'triangles_precalcs'
	get 'precalc/practice/sine/:id'              => 'precalcs#sine',            as: 'sine_precalcs'
	get 'precalc/practice/trig/:id'              => 'precalcs#trig',            as: 'trig_precalcs'
	get 'precalc/practice/systems/:id'           => 'precalcs#systems',         as: 'systems_precalcs'

	get 'proofs/dashboard/:id'                   => 'proofs#dashboard',         as: 'dash_proofs'
	get 'proofs/quiz/:id'                        => 'proofs#quiz',              as: 'quiz_proofs'
	get 'proofs/practice/:id'                    => 'proofs#practice',          as: 'practice_proofs'
	get 'proofs/practice/logic/:id'              => 'proofs#logic',             as: 'logic_proofs'
	get 'proofs/practice/induction/:id'          => 'proofs#induction',         as: 'induction_proofs'
	get 'proofs/practice/relations/:id'          => 'proofs#relations',         as: 'relations_proofs'
	get 'proofs/practice/functions/:id'          => 'proofs#functions',         as: 'functions_proofs'
	get 'proofs/practice/cardinality/:id'        => 'proofs#cardinality',       as: 'cardinality_proofs'
	get 'proofs/practice/modulo/:id'             => 'proofs#modulo',            as: 'modulo_proofs'
	get 'proofs/practice/algebra/:id'            => 'proofs#algebra',           as: 'algebra_proofs'

	resource :sessions, only: [:new, :create, :destroy]

	root 'sessions#new'

end

app/models/precalc.rb
class Precalc < ActiveRecord::Base

end

app/controllers/precalcs_controller.rb
class PrecalcsController < ApplicationController

	def index
		@precalcs = Precalc.all
	end

	def dashboard
		@user = User.find(session['user_id'])
	end

	def practice
		@user = User.find(session['user_id'])
		@precalcs = Precalc.where(question_type:'practice')
	end

	def functions
		@user = User.find(session['user_id'])
		@precalcs = Precalc.where(question_type:'practice', module_name:'functions')
	end

	def logs
		@user = User.find(session['user_id'])
		@precalcs = Precalc.where(question_type:'practice', module_name:'logs')
	end

	def triangles
		@user = User.find(session['user_id'])
		@precalcs = Precalc.where(question_type:'practice', module_name:'triangles')
	end

	def sine
		@user = User.find(session['user_id'])
		@precalcs = Precalc.where(question_type:'practice', module_name:'sine')
	end

	def trig
		@user = User.find(session['user_id'])
		@precalcs = Precalc.where(question_type:'practice', module_name:'trig')
	end

	def systems
		@user = User.find(session['user_id'])
		@precalcs = Precalc.where(question_type:'practice', module_name:'systems')
	end

	def quiz
		@user = User.find(session['user_id'])
		@precalcs = Precalc.where(question_type:'quiz')
	end

	def new
		@user = User.find(session['user_id'])
		@precalc = Precalc.new
	end

	def create
		@precalc = Precalc.create(precalc_params)
		if @precalc.save
			redirect_to precalcs_path
		else
			render 'new'
		end
	end

	def show
		@precalc = Precalc.find(params[:id])
	end

	private
	def precalc_params
		params.require(:lower).permit(:user_id, :question_type, :question, :solution, :answer_choices,
																	:correct, :hint)
	end
	
end

app/helpers/precalcs_helper.rb
module PrecalcsHelper
end

app/views/precalcs/_nav.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<button type="button" class="btn btn-default navbar-btn navbar-right">
				<%= link_to 'Dashboard', user_path(session['user_id']), :style => 'font-decoration:none;color:#26aa30' %>
			</button>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
						Subjects <span class="caret"></span>
					</a>
					<ul class="dropdown-menu" role="menu">
						<li><%= link_to 'Algebra I', dash_algebras_path(session['user_id']) %></li>
						<li><%= link_to 'Finite Math', dash_business_maths_path(session['user_id']) %></li>
						<li><%= link_to 'ISEE - Lower', dash_lowers_path(session['user_id']) %></li>
						<li><%= link_to 'ISEE - Upper', dash_uppers_path(session['user_id']) %></li>
						<li><%= link_to 'Linear Algebra', dash_linears_path(session['user_id']) %></li>
						<li><%= link_to 'Precalculus', dash_precalcs_path(session['user_id']) %></li>
						<li><%= link_to 'Proof Writing', dash_proofs_path(session['user_id']) %></li>
					</ul>
				</li>
			</ul>

			<div class="btn-group">
				<button class="btn btn-info btn-sm">
					<%= link_to 'Precalculus', dash_precalcs_path(session['user_id']), style:"color:#f0f0f0" %>
				</button>
				<button class="btn btn-info btn-sm dropdown-toggle" data-toggle="dropdown"> <span class="caret"></span>
				</button>
				<ul class="dropdown-menu">
					<li><%= link_to 'Functions and polynomials', functions_precalcs_path(session['user_id']) %></li>
					<li><%= link_to 'Logarithms', logs_precalcs_path(session['user_id']) %></li>
					<li><%= link_to 'Right triangle geometry and trigonometric functions for the unit circle', triangles_precalcs_path(session['user_id']) %></li>
					<li><%= link_to 'The graphs of sine and cosine', sine_precalcs_path(session['user_id']) %></li>
					<li><%= link_to 'Trigonometric functions and equations', trig_precalcs_path(session['user_id']) %></li>
					<li><%= link_to 'Linear and nonlinear systems', systems_precalcs_path(session['user_id']) %></li>
				</ul>
			</div>

			<!--<ul class="nav navbar-nav navbar-right">-->
			<!--<li>Hello, <%#= @user.first_name.capitalize %>!</li>-->
			<!--</ul>-->
			<ul class="nav navbar-nav navbar-right"  style="color:#26aa30">
				<li>
					<!--<a href="#editProfileModal" data-toggle="modal" data-target="#editProfileModal">Edit profile</a>-->
					<%#= link_to 'Edit profile', edit_user_path(session['user_id']) %>
					<button type="button" class="btn btn-default navbar-btn navbar-right">
						<a href="#editProfileModal" data-toggle="modal" data-target="#editProfileModal">Edit profile</a>
					</button>
				</li>
				<li>
					<p class="navbar-name">Hello, <%= @user.first_name.capitalize %>!</p>
				</li>
			</ul>

			<button type="button" class="btn btn-default navbar-btn navbar-right">
				<%= link_to 'Log out', sessions_path, method: :delete, :style => 'font-decoration:none;color:#26aa30' %>
			</button>
		</div>
	</div>
</nav>


<div class="modal fade" id="editProfileModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h4 class="modal-title">Edit profile</h4>
			</div>
			<div class="modal-body">
				<div class="ruby-form">
					<%= form_for @user do |f| %>
						<%= f.text_field :first_name,   placeholder: 'First name', class:'form-input' %>
						<%= f.text_field :last_name,    placeholder: 'Last name',  class:'form-input' %><br><br>
						<%= f.text_field :email,        placeholder: 'Email',      class:'form-input' %><br><br>
						<%= f.submit 'Update profile!', 												   class:'btn btn-default btn-login btn-lg' %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/precalcs/dashboard.html.erb
<%= render 'nav' %>

  <div class="circles"> 
	<div class="row">
		<%= link_to practice_precalcs_path(session['user_id']) do %> 
			<div class="subject-circle col-md-6"> 
				<div class="subject">Practice Problems</div> 
			</div> 
		<% end %>
		<%= link_to quiz_precalcs_path(session['user_id']) do %> 
			<div class="subject-circle col-md-6"> 
				<div class="subject">Quiz</div>
			</div> 
		<% end %> 
	</div> 
</div>

  <ol class="breadcrumb"> 
	<li><%= link_to 'Dashboard', user_path(session['user_id']) %></li>
	<li class="active">Precalculus</li> 
</ol>

app/views/precalcs/functions.html.erb
<%= render 'nav' %>

<!--find a random entry in the array of available ids-->
<% ids = Array.new %>
<% @precalcs.each do |p| %>
	<% ids.push(p.id) %>
<% end %>
<% id = ids.sample %>

<div class="precalc-practice-question">
	<%= @precalcs.find(id).question %>
		<br><br>
	<button type="button" class="btn btn-default" id="precalc-solution-button">Solution</button>

	<% if @precalcs.find(id).hint != nil %>
		<button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#hintModal">
			Hint
		</button>
		<!-- Modal -->
		<div class="modal fade" id="hintModal" tabindex="-1" role="dialog" aria-labelledby="hintModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4 class="modal-title" id="hintModalLabel">Hint</h4>
					</div>
					<div class="modal-body">
						<%= @precalcs.find(id).hint %>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

<div id="practice-solutions-box" class="practice-solution">
	<div class="practice-solution-step" style="display:none;">
		<ol>
			<% @precalcs.find(id).solution.each do |step| %>
				<% index = @precalcs.find(id).solution.index(step) %>
				<li id="Step<%= index+1 %>"><%= step %></li>
			<% end %>
		</ol>
		<br><br>
		<button type="button" class="btn btn-default btn-sm" id="step" onclick="ShowStep()" disabled="true">
			show next step
		</button>
		<button type="button" class="btn btn-default btn-sm" id="reset" onclick="ResetSteps()" disabled="true">
			reset steps
		</button>
	</div>
</div>

<div style="margin: 0 auto;width:20%;">
	<div class="row">
		<div class="col-md-6">
			<button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#unitCircleModal">
				Unit circle
			</button>
			<!-- Modal -->
			<div class="modal fade" id="unitCircleModal" tabindex="-1" role="dialog" aria-labelledby="unitCircleModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h4 class="modal-title" id="unitCircleModalLabel">Unit circle</h4>
						</div>
						<div class="modal-body">
							<%= image_tag('unit-circle.png') %>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-6">
			<div class="next-question">
				<button type="button" class="btn btn-success btn-lg">
					<%= link_to 'Next question', functions_precalcs_path(session['user_id']), :style => 'font-decoration:none; color:#f0f0f0' %>
				</button>
			</div>
		</div>
	</div>
</div>

<ol class="breadcrumb">
	<li><%= link_to 'Dashboard', user_path(session['user_id']) %></li>
	<li><%= link_to 'Precalculus', dash_precalcs_path(session['user_id']) %></li>
	<li><%= link_to 'Practice', practice_precalcs_path(session['user_id']) %></li>
	<li class="active">Functions and polynomials</li>
</ol>

app/views/precalcs/logs.html.erb
<%= render 'nav' %>

<!--find a random entry in the array of available ids-->
<% ids = Array.new %>
<% @precalcs.each do |p| %>
	<% ids.push(p.id) %>
<% end %>
<% id = ids.sample %>

<div class="precalc-practice-question">
	<%= @precalcs.find(id).question %>
	<br><br>
	<button type="button" class="btn btn-default" id="precalc-solution-button">Solution</button>

	<% if @precalcs.find(id).hint != nil %>
		<button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#hintModal">
			Hint
		</button>
		<!-- Modal -->
		<div class="modal fade" id="hintModal" tabindex="-1" role="dialog" aria-labelledby="hintModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4 class="modal-title" id="hintModalLabel">Hint</h4>
					</div>
					<div class="modal-body">
						<%= @precalcs.find(id).hint %>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

<div id="practice-solutions-box" class="practice-solution">
	<div class="practice-solution-step" style="display:none;">
		<ol>
			<% @precalcs.find(id).solution.each do |step| %>
				<% index = @precalcs.find(id).solution.index(step) %>
				<li id="Step<%= index+1 %>"><%= step %></li>
			<% end %>
		</ol>
		<br><br>
		<button type="button" class="btn btn-default btn-sm" id="step" onclick="ShowStep()" disabled="true">
			show next step
		</button>
		<button type="button" class="btn btn-default btn-sm" id="reset" onclick="ResetSteps()" disabled="true">
			reset steps
		</button>
	</div>
</div>

<div style="margin: 0 auto;width:50%;">
	<div class="row row-centered">
		<div class="col-md-4 col-centered">
			<button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal">
				Unit circle
			</button>
			<!-- Modal -->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h3 class="modal-title" id="myModalLabel">Unit circle</h3>
						</div>
						<div class="modal-body">
							<%= image_tag('unit-circle.png') %>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-4 col-centered">
			<button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#trigModal">
				Logarithms
			</button>
			<!-- Modal -->
			<div class="modal fade" id="trigModal" tabindex="-1" role="dialog" aria-labelledby="trigModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h3 class="modal-title" id="trigModalLabel">Logarithms</h3>
						</div>
						<div class="modal-body">
							<h3>Properties of Logarithms</h3>
							<p>$$\begin{array}{crlc} \log_b{b} = 1 & \log_b{1} = 0 & b^{\log_b{x}} = x & \log_b{b^x} = x
								\end{array}$$</p>
							<p>$$\begin{array}{rl}\log_{b}{a^r} = r \log_b{a} & \log_b{u} = \dfrac{\log_a{u}}{\log_a{b}}
								\end{array}$$</p>
							<p>$$\begin{array}{rl}\log_b{uv} = \log_b{u} + \log_b{v} & \log_b{\frac{u}{v}} = \log_b{u} - \log_b{v} \end{array}$$</p>
							<h3>Interest Formulas</h3>
							<p>$$\begin{array}{cc} A = P\left(1+\frac{r}{n}\right)^{nt} & A = Pe^{rt} \end{array}$$</p>
							</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-4 col-centered">
			<div class="next-question">
				<button type="button" class="btn btn-success btn-lg">
					<%= link_to 'Next question', logs_precalcs_path(session['user_id']), :style => 'font-decoration:none;
					color:#f0f0f0' %>
				</button>
			</div>
		</div>
	</div>
</div>

<ol class="breadcrumb">
	<li><%= link_to 'Dashboard', user_path(session['user_id']) %></li>
	<li><%= link_to 'Precalculus', dash_precalcs_path(session['user_id']) %></li>
	<li><%= link_to 'Practice', practice_precalcs_path(session['user_id']) %></li>
	<li class="active">Logarithms</li>
</ol>

app/views/precalcs/new.html.erb
<%= render 'users/nav' %>
<% if @user.is_admin == true %>

	<div class="row">
		<div class="col-md-6 text-center"><h1 class="heading">Add a precalculus practice problem</h1></div>
		<div class="col-md-6 text-center"><%= link_to 'Cancel', users_path(session['user_id']) %></div>
	</div>

	<%= form_for @precalc do |f| %>
		<div>
			<%= f.radio_button :question_type, 'practice' %><%= f.label :question_type, 'Practice', value: 'practice' %>
			<%= f.radio_button :question_type, 'quiz' %><%= f.label :question_type, 'Quiz', value: 'quiz' %><br><br>

			<%= f.text_area :question,    placeholder: 'Enter the question.' %><br>

			Enter steps of the solution:
				<%= f.text_area :solution, size: 15, name: 'solution[]' %><br>

			<%#= f.text_field :director, placeholder: 'Director' %><br>
			<%#= f.text_field :writer,   placeholder: 'Writer' %><br><br>

			<%= f.submit 'Add this problem!' %><br>

		</div>
	<% end %>

<% else %>

	<h1>You can't view this page!</h1>

<% end %>

app/views/precalcs/practice.html.erb
<%= render 'nav' %>

<div class="circles">
	<div class="row">
		<%= link_to functions_precalcs_path(session['user_id']) do %>
			<div class="subject-circle col-md-3">
				<div class="subject">Functions and polynomials</div>
			</div>
		<% end %>

		<%= link_to logs_precalcs_path(session['user_id']) do %>
			<div class="subject-circle col-md-3">
				<div class="subject">Logarithms</div>
			</div>
		<% end %>

		<%= link_to triangles_precalcs_path(session['user_id']) do %>
			<div class="subject-circle col-md-3">
				<div class="subject">Right triangle geometry and trigonometric functions for the unit circle</div>
			</div>
		<% end %>

		<%= link_to sine_precalcs_path(session['user_id']) do %>
			<div class="subject-circle col-md-3">
				<div class="subject">The graphs of sine and cosine</div>
			</div>
		<% end %>
	</div>

	<div class="row">
		<%= link_to trig_precalcs_path(session['user_id']) do %>
			<div class="subject-circle col-md-3">
				<div class="subject">Trigonometric identities and equations</div>
			</div>
		<% end %>

		<%= link_to systems_precalcs_path(session['user_id']) do %>
			<div class="subject-circle col-md-3">
				<div class="subject">Linear and nonlinear systems of equations and inequalities</div>
			</div>
		<% end %>
	</div>
</div>

<ol class="breadcrumb">
	<li><%= link_to 'Dashboard', user_path(session['user_id']) %></li>
	<li><%= link_to 'Precalculus', dash_precalcs_path(session['user_id']) %></li>
	<li class="active">Practice</li>
</ol>

app/views/precalcs/sine.html.erb
<%= render 'nav' %>

<!--find a random entry in the array of available ids-->
<% ids = Array.new %>
<% @precalcs.each do |p| %>
	<% ids.push(p.id) %>
<% end %>
<% id = ids.sample %>

<div class="precalc-practice-question">
	<%= @precalcs.find(id).question %>
	<br><br>
	<button type="button" class="btn btn-default" id="precalc-solution-button">Solution</button>

	<% if @precalcs.find(id).hint != nil %>
		<button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#hintModal">
			Hint
		</button>
		<!-- Modal -->
		<div class="modal fade" id="hintModal" tabindex="-1" role="dialog" aria-labelledby="hintModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4 class="modal-title" id="hintModalLabel">Hint</h4>
					</div>
					<div class="modal-body">
						<%= @precalcs.find(id).hint %>
					</div>
				</div>
			</div>
		</div>
	<% end %>

</div>

<div id="practice-solutions-box" class="practice-solution">
	<div class="practice-solution-step" style="display:none;">
		<ol>
			<% @precalcs.find(id).solution.each do |step| %>
				<% index = @precalcs.find(id).solution.index(step) %>
				<li id="Step<%= index+1 %>"><%= step %></li>
			<% end %>
		</ol>
		<br><br>
		<button type="button" class="btn btn-default btn-sm" id="step" onclick="ShowStep()" disabled="true">
			show next step
		</button>
		<button type="button" class="btn btn-default btn-sm" id="reset" onclick="ResetSteps()" disabled="true">
			reset steps
		</button>
	</div>
</div>

<div style="margin: 0 auto;width:20%;">
	<div class="row">
		<div class="col-md-6">
			<button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal">
				Unit circle
			</button>
			<!-- Modal -->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<h4 class="modal-title" id="myModalLabel">Unit circle</h4>
						</div>
						<div class="modal-body">
							<%= image_tag('unit-circle.png') %>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-6">
			<div class="next-question">
				<button type="button" class="btn btn-success btn-lg">
					<%= link_to 'Next question', sine_precalcs_path(session['user_id']), :style => 'font-decoration:none; color:#f0f0f0' %>
				</button>
			</div>
		</div>
	</div>
</div>


<ol class="breadcrumb">
	<li><%= link_to 'Dashboard', user_path(session['user_id']) %></li>
	<li><%= link_to 'Precalculus', dash_precalcs_path(session['user_id']) %></li>
	<li><%= link_to 'Practice', practice_precalcs_path(session['user_id']) %></li>
	<li class="active">The graphs of sine and cosine</li>
</ol>